Back-end/ASP.net/SmartDLU - Project 2018/DLU/Controllers/ThiThu/ThiThu_Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using DataAccess;


namespace DLU.Controllers.ThiThu
{
    public class ThiThu_Controller : Controller
    {
        // GET: ThiThu_
        QuanLyThi qlt = new QuanLyThi();
        QL_MonHoc qlmonhoc = new QL_MonHoc();
        ThiThuMethods tt = new ThiThuMethods();
        KetQuaThiThuMethods kqtt = new KetQuaThiThuMethods();

        public ActionResult Index()
        {
            ViewBag.MonHoc = qlmonhoc.Get_DanhSach_MonHoc();
            return View();
        }
        
        public ActionResult ChonBoDe(FormCollection form)
        {
            int idMonHoc = Convert.ToInt32(form["Idmonhoc"]);
            List<BODE> bode = qlt.GetBoDeByIDMonHoc(idMonHoc);
            ViewBag.BoDe = bode;
            return View();
        }

        public ActionResult ChonDe(FormCollection form)
        {
            int idBoDe = Convert.ToInt32(form["idBoDe"]);
            string thoigian = form["idThoiGian"];
            qlt.CapNhatThoiGian(thoigian + ":00");
            List<DETHI> dethi = qlt.SelectDeThiByBoDe(idBoDe);
            ViewBag.DeThi = dethi;
            return View();
        }
        public ActionResult LuuDe(FormCollection form)
        {
            qlt.CapNhatDeThi(Convert.ToInt32(form["idDe"]));
            int IDthithu = tt.Them_ThiThu(new THITHU(-1, GetSession.IDDETHI));
            qlt.CapNhatLichThi(IDthithu);
            QL_CauHoi ql = new QL_CauHoi();
            List<CAUHOI> dsCauHoi = new List<CAUHOI>();
            dsCauHoi = ql.GetByIdDeThi(Convert.ToInt32(GetSession.IDDETHI));
            ViewBag.dsCauHoi = dsCauHoi;
            //Lấy danh sách câu trả lời
            QL_CauTraLoi qlCTL = new QL_CauTraLoi();
            List<CAUTRALOI> dsCauTraLoi = qlCTL.GetByIdDeThi(Convert.ToInt32(GetSession.IDDETHI));
            ViewBag.dsCauTraLoi = dsCauTraLoi;
            ViewBag.MADE = Convert.ToInt32(GetSession.IDDETHI);
            for (int i = 1; i <= dsCauHoi.Count; i++)
            {
                kqtt.Them_KetQuaThiThu(new KETQUATHITHU(GetSession.IDLICHTHI, i, -1));
            }
            return RedirectToAction("ThiThu");
        }

        public ActionResult ThiThu(FormCollection form)
        {
            //Lấy danh sách câu hỏi
            QL_CauHoi ql = new QL_CauHoi();
            List<CAUHOI> dsCauHoi = new List<CAUHOI>();
            dsCauHoi = ql.GetByIdDeThi(Convert.ToInt32(GetSession.IDDETHI));
            ViewBag.dsCauHoi = dsCauHoi;
            //Lấy danh sách câu trả lời
            QL_CauTraLoi qlCTL = new QL_CauTraLoi();
            List<CAUTRALOI> dsCauTraLoi = qlCTL.GetByIdDeThi(Convert.ToInt32(GetSession.IDDETHI));
            ViewBag.dsCauTraLoi = dsCauTraLoi;
            ViewBag.MADE = Convert.ToInt32(GetSession.IDDETHI);
            if (GetSession.THOIGIANCONLAI != null)
            {
                string[] time = Regex.Split(GetSession.THOIGIANCONLAI, ":");
                ViewBag.min = time[0];
                ViewBag.sec = time[1];
            }
            return View();
        }

        public ActionResult KetQuaThiThu()
        {
            //Lấy danh sách câu hỏi
            QL_CauHoi ql = new QL_CauHoi();
            List<CAUHOI> dsCauHoi = new List<CAUHOI>();
            dsCauHoi = ql.GetByIdDeThi(GetSession.IDDETHI);
            ViewBag.dsCauHoi = dsCauHoi;
            //Lấy danh sách câu trả lời
            QL_CauTraLoi qlCTL = new QL_CauTraLoi();
            List<CAUTRALOI> dsCauTraLoi = qlCTL.GetByIdDeThi(GetSession.IDDETHI);
            ViewBag.dsCauTraLoi = dsCauTraLoi;
            int tongsocauhoi = dsCauHoi.Count;
            List<KETQUATHITHU> kqt = kqtt.Get_DanhSach_By_ID(GetSession.IDLICHTHI);
            int soCauDung = 0;
            foreach (var item in kqt)
            {
                if (item.CAUTRALOI != -1)
                {
                    List<CAUTRALOI> ctl = qlCTL.Get_DanhSach_By_ID(item.CAUTRALOI);
                    if (ctl.First().DUNGSAI == true)
                        soCauDung++;
                }
            }
            double diem = 10.0 / (double)tongsocauhoi;
            ViewBag.DSKetQuaThi = kqt;
            ViewBag.Diem = String.Format("{0:0.##}", soCauDung * diem);
            ViewBag.KQ = soCauDung + "/" + dsCauHoi.Count;
            return View();
        }


        // Cập nhật câu trả lời của thí sinh
        [HttpPost]
        public void UpdateStudentTest(FormCollection form)
        {
            string answer = form["answer"];
            int id_quest = Convert.ToInt32(form["id"]);
            answer = answer.Trim();
            string time = form["min"] + ":" + form["sec"];
            //Model.UpdateStudentTest(answer);
            //Model.UpdateTiming(time);
            kqtt.Sua_KetQuaThiThu(new KETQUATHITHU(GetSession.IDLICHTHI,id_quest,Convert.ToInt32(answer)));
        }
    }
}

Back-end/ASP.net/SmartDLU - Project 2018/DLU/Views/ThiThu_/ChonBoDe.cshtml
@using DataAccess;
@{
    ViewBag.Title = "ChonBoDe";
    Layout = "~/Views/Shared/_LayoutCauHoiOnTap.cshtml";
    List<BODE> bode = ViewBag.BoDe;
}


<div class="grid-content">
   
    <div id="col-2" class="col-12 col-md-9 including fadeIn animated col-list-quiz">
        <div id="multiple">

            <div class="heading heading-white">
                <h1><i class="glyphicon glyphicon-align-right"></i> Đề thi </h1>
                <hr>
            </div>

            <div id="quizs" class="new many online">
                @{
                    foreach (var item in bode)
                    {
                <div class="quiz including" style="border-top: 3px solid #f8a31c">
                    <div class="including">
                        <h1 class="pull-left"><a href="#">@item.TENBODE</a></h1>
                        <div class="pull-right bookmark">
                            <a href="#" data-id="215"><i class="glyphicon glyphicon-bookmark" class="a-bookmark"></i></a>
                        </div>
                    </div>
                    @using (Html.BeginForm("ChonDe", "ThiThu_", FormMethod.Post))
                    {
                        <input type="text" name="idBoDe" value="@item.IDBODE" hidden>
                        <input type="text" name="idThoiGian" value="@item.THOIGIANLAMBAI_PHUT_" hidden>
                        <button class="btn btn-default pull-right" style="background: #f8a31c">
                            Truy cập
                        </button>
                    }
                </div>
                    }
                }
                <div class="full-width including">
                    <div class="text-center" id="pagination">
                        <div class="pagination">
                            <ul class="pagination">
                                <li class="disabled"><span>&laquo;</span></li>
                                <li class="active"><span>1</span></li>
                                <li><a href="trac-nghiem18c0.html?p&amp;page=2">2</a></li>
                                <li><a href="trac-nghiem42ef.html?p&amp;page=3">3</a></li>
                                <li><a href="trac-nghiem5825.html?p&amp;page=4">4</a></li>
                                <li><a href="trac-nghiem461b.html?p&amp;page=5">5</a></li>
                                <li><a href="trac-nghiemf4db.html?p&amp;page=6">6</a></li>
                                <li><a href="trac-nghiem4890.html?p&amp;page=7">7</a></li>
                                <li><a href="trac-nghiem0010.html?p&amp;page=8">8</a></li>
                                <li><a href="trac-nghiem796d.html?p&amp;page=9">9</a></li>
                                <li><a href="trac-nghiembc0d.html?p&amp;page=10">10</a></li>
                                <li><a href="trac-nghiem18c0.html?p&amp;page=2">&raquo;</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="assets/js/newstyle/default-main.js"></script>
    <script type="text/javascript">
		$(document).ready(function () {
			//$(".col-1-slide").menuslide({element_action:'#slide-menu-1'});
			tabs = $("#multiple").tabs({ redirect: true });

			category = $("#category-all");
			category.closest('ul').find('li').removeClass('active');//Loại bỏ active
			li_select = $("#category-all").closest('li');//Lựa chọn select
			color = li_select.attr('data-color');//Lấy màu
			li_select.addClass('active');
			$(".list-category li.active").css('border-right', '3px solid ' + color);//Thêm màu cho active

			$("#search-form input[name=text_search]").live('click', function () {
				$("#search-form").find('.select').fadeIn();
			});
			$("#nav-category").addClass('active');
		});
    </script>
</div>

Back-end/ASP.net/SmartDLU - Project 2018/DLU/Views/ThiThu_/ChonDe.cshtml
@using DataAccess;
@{
    ViewBag.Title = "ChonDe";
    Layout = "~/Views/Shared/_LayoutCauHoiOnTap.cshtml";
    List<DETHI> dethi = ViewBag.DeThi;
}

<div class="grid-content">

    <div id="col-2" class="col-12 col-md-9 including fadeIn animated col-list-quiz">
        <div id="multiple">

            <div class="heading heading-white">
                <h1><i class="glyphicon glyphicon-align-right"></i> Đề thi </h1>
                <hr>
            </div>

            <div id="quizs" class="new many online">
                @{
                    foreach (var item in dethi)
                    {
                <div class="quiz including" style="border-top: 3px solid #f8a31c">
                    <div class="including">
                        <h1 class="pull-left"><a href="#">@item.TENDETHI</a></h1>
                        <div class="pull-right bookmark">
                            <a href="#" data-id="215"><i class="glyphicon glyphicon-bookmark" class="a-bookmark"></i></a>
                        </div>
                    </div>
                    @using (Html.BeginForm("LuuDe", "ThiThu_", FormMethod.Post))
                    {
                        <input type="text" name="idDe" value="@item.IDMADE" hidden>
                        <button class="btn btn-default pull-right" style="background: #f8a31c">
                            Truy cập
                        </button>
                    }
                </div>
                    }
                }
                <div class="full-width including">
                    <div class="text-center" id="pagination">
                        <div class="pagination">
                            <ul class="pagination">
                                <li class="disabled"><span>&laquo;</span></li>
                                <li class="active"><span>1</span></li>
                                <li><a href="trac-nghiem18c0.html?p&amp;page=2">2</a></li>
                                <li><a href="trac-nghiem42ef.html?p&amp;page=3">3</a></li>
                                <li><a href="trac-nghiem5825.html?p&amp;page=4">4</a></li>
                                <li><a href="trac-nghiem461b.html?p&amp;page=5">5</a></li>
                                <li><a href="trac-nghiemf4db.html?p&amp;page=6">6</a></li>
                                <li><a href="trac-nghiem4890.html?p&amp;page=7">7</a></li>
                                <li><a href="trac-nghiem0010.html?p&amp;page=8">8</a></li>
                                <li><a href="trac-nghiem796d.html?p&amp;page=9">9</a></li>
                                <li><a href="trac-nghiembc0d.html?p&amp;page=10">10</a></li>
                                <li><a href="trac-nghiem18c0.html?p&amp;page=2">&raquo;</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="assets/js/newstyle/default-main.js"></script>
    <script type="text/javascript">
		$(document).ready(function () {
			//$(".col-1-slide").menuslide({element_action:'#slide-menu-1'});
			tabs = $("#multiple").tabs({ redirect: true });

			category = $("#category-all");
			category.closest('ul').find('li').removeClass('active');//Loại bỏ active
			li_select = $("#category-all").closest('li');//Lựa chọn select
			color = li_select.attr('data-color');//Lấy màu
			li_select.addClass('active');
			$(".list-category li.active").css('border-right', '3px solid ' + color);//Thêm màu cho active

			$("#search-form input[name=text_search]").live('click', function () {
				$("#search-form").find('.select').fadeIn();
			});
			$("#nav-category").addClass('active');
		});
    </script>
</div>

Back-end/ASP.net/SmartDLU - Project 2018/DLU/Views/ThiThu_/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutCauHoiOnTap.cshtml";
    var monhoc = ViewBag.MonHoc;
}

<div class="grid-content">
    <script type="text/javascript" src="assets/js/quiz2/scripts.js"></script>
    <div id="col-2" class="col-lg-12 col-md-9 including fadeIn animated col-list-quiz">
        <!--Đề thi online ở trang chủ-->


        <div class="including" id="university" style="padding:2%;">

            <div class="row">
                <div class="heading heading-white">
                    <h1><i class="glyphicon glyphicon-tower"></i> Môn Học</h1>
                    <hr>
                </div>
                @{
                    foreach (var item in monhoc)
                    {
                        <div class="col col-md-4 col-xs-6">
                            <hr>
                            <h4 class="color-red ">@item.TENMONHOC</h4>
                            <div class="glass-link">

                                @using (Html.BeginForm("ChonBoDe", "ThiThu_", FormMethod.Post))
                                {
                                    <input type="text" name="Idmonhoc" value="@item.IDMONHOC" hidden>
                                    <button class="btn btn-default pull-right" style="background: #f8a31c">
                                        Truy cập
                                    </button>
                                }
                                <br />

                            </div>
                            <hr />
                        </div>
                    }
                }
            </div>

        </div>

    </div>

    <script type="text/javascript" src="assets/js/newstyle/default-main.js"></script>
    <script type="text/javascript">
		$(document).ready(function () {
			$("select[name=year]").val('2013');
			$("#nav-university").addClass('active');
		});
    </script>
</div>

Back-end/ASP.net/SmartDLU - Project 2018/DLU/Views/ThiThu_/KetQuaThiThu.cshtml
@using DataAccess;
@{
    ViewBag.Title = "KetQuaThiThu";
    Layout = "~/Views/Shared/_LayoutCauHoiOnTap.cshtml";
    var dsCauHoi = ViewBag.dsCauHoi as List<CAUHOI>;
    var dsCauTraLoi = ViewBag.dsCauTraLoi as IEnumerable<CAUTRALOI>;
    var dsKetQuaThi = ViewBag.DSKetQuaThi as List<KETQUATHITHU>;
}

<div class="grid-content">
    <script type="text/javascript" src="assets/js/quiz2/scripts.js"></script>
    <div class="col-12 col-md-12 including fadeIn animated col-list-quiz">
        <div id="multiple">

            <div class="heading heading-white">
                <h1><i class="glyphicon glyphicon-align-right"></i> Kết quả</h1>
                <hr>
            </div>
            <h2><i class="glyphicon glyphicon-align-right"></i> Điểm :@ViewBag.Diem</h2>
            <h2><i class="glyphicon glyphicon-align-right"></i> Số câu đúng :@ViewBag.KQ</h2>

            <h2><i></i> Đáp án đúng:<span style="color:green"> Xanh</span></h2>
            <h2><i></i> Đáp án thí sinh: <span style="color:red"> Đỏ</span></h2>
            <section class="forms full_test" id="main">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-7">
                            <div class="card">
                                <div class="card-body">
                                    <form id="testing_form" action="" method="POST">
                                        <input type="hidden" name="test_id" value="14682" />
                                        <input type="hidden" name="log_id" value="9852" />
                                        <input type="hidden" name="token" value="f74d049c17fab4b5c89a39fccd85b949">
                                        <div class="col-md-8 col-sm-8 col-xs-12">
                                            <div class="col_box_test">
                                                <div class="clear col_box_baihoc_view" id="fulltest_content">
                                                    @{

                                                        var i = 1;
                                                        foreach (var cauHoi in dsCauHoi)
                                                        {
                                                            var j = 1;
                                                            <div data-part="@i" class="question fullest_page_@i" data-page="@i" style="display: block;"
                                                                 id="test_question_128051">
                                                                <div class="myquestionarea">
                                                                    <div id="testing_answer_128051_@i">
                                                                        <div class="question_number"><b>Câu @i: </b><span>@cauHoi.NOIDUNGCAUHOI</span></div>
                                                                        @foreach (var ctl in dsCauTraLoi)
                                                                        {
                                                                        if (cauHoi.IDCAUHOI == ctl.IDCAUHOI)
                                                                        {
                                                                        foreach (var kqt in dsKetQuaThi)
                                                                        {
                                                                        if (kqt.INDEXCAUHOI == i)
                                                                        {
                                                                        if (kqt.CAUTRALOI == ctl.IDCAUTL && !ctl.DUNGSAI)
                                                                        {
                                                                        <label class="fulltest_answer_label active">
                                                                            <input type="radio" data-iquestion="@i" data-question="128051"
                                                                                   name="answer[128051][@i]" value="@ctl.INDEXCTL" checked="checked">
                                                                            <strong>@CHUYENDOI.DoiCoSo(@j)</strong> <span style="color:red">
                                                                                @ctl.NOIDUNGCAUTL.Trim()
                                                                            </span>
                                                                        </label>
                                                                        }
                                                                        else if (ctl.DUNGSAI)
                                                                        {
                                                                        <label class="fulltest_answer_label active">
                                                                            <input type="radio" data-iquestion="@i" data-question="128051"
                                                                                   name="answer[128051][@i]" value="@ctl.INDEXCTL" checked="checked">
                                                                            <strong style="background: #03ec07; color: #fff; border: 1px solid #02f906;">@CHUYENDOI.DoiCoSo(@j)</strong> <span style="color:green">
                                                                                @ctl.NOIDUNGCAUTL.Trim()
                                                                            </span>
                                                                        </label>
                                                                        }
                                                                        else
                                                                        {
                                                                        <label class="fulltest_answer_label">
                                                                            <input type="radio" data-iquestion="@i" data-question="128051"
                                                                                   name="answer[128051][@i]" value="@ctl.INDEXCTL">
                                                                            <strong>@CHUYENDOI.DoiCoSo(@j)</strong> <span>
                                                                                @ctl.NOIDUNGCAUTL.Trim()
                                                                            </span>
                                                                        </label>
                                                                        }

                                                                        }
                                                                        }

                                                                        j = j + 1;

                                                                        }

                                                                        }
                                                                    </div>
                                                                </div>
                                                            </div> i = i + 1;
                                                        }
                                                    }
                                                </div>
                                            </div><!-- End -->
                                        </div>
                                    </form>
                                </div>

                            </div>
                        </div>
                    </div>

                </div>
                <div id="support_online"></div>
                <div class="modal fade" id="modal_message" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <h4 class="modal-title" id="myModalLabel">Thông báo</h4>
                            </div>
                            <div class="modal-body">

                            </div>
                            <div class="modal-footer"></div>
                        </div>
                    </div>
                </div>
                <div id="fb-root"></div>
            </section>
        </div>
    </div>
</div>